stages:
  - build
  - test
  - deploy 

build_dependencies:
  stage: build
  script:
    - echo "Start building dependencies ...."
    - mvn clean install
    - echo "Done"

build_docker_image:
  stage: build
  script:
    - echo "Start building docker image ..."
    - docker-compose up -d 
    - docker-compose ps
    - echo "Done"

test_internal_API:
  stage: test
  script:
    - echo "Start testing internal API..."
    - mvn test
    - echo "Done"

deploy_project:
  stage: deploy
  script:
    - echo "Start deploying ..."
    - echo "Done"