stages:
  - build
  - test
  - deploy 

build_dependencies:
  stage: build
  script:
    - echo "Start building dependencies ...."
    - echo "Done"

build_docker_image:
  stage: build
  script:
    - echo "Start building docker image ..."
    - echo "Done"

test_project:
  stage: test
  script:
    - echo "Start testing ..."
    - echo "Done"

deploy_project:
  stage: deploy
  script:
    - echo "Start deploying ..."
    - echo "Done"