stages:
  - build
  - test
  - deploy 

build_dependencies:
  stage: build
  script:
    - echo "Start building dependencies ...."
    - mvn clean install
    - echo "Done"

build_docker_image:
  image: AWSCronJobScheduler:latest
  stage: build
  script:
    - echo "Start building docker image ..."
    - docker-compose up -d 
    - docker-compose ps
    - echo "Done"

test_internal_API:
  stage: test
  script:
    - echo "Start testing internal API..."
    - mvn test
    - echo "Done"

deploy_project:
  image: AWSCronJobScheduler:latest 
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$CD_DOCKER_HUB_USER" -p "$CD_DOCKER_HUB_PASSWORD"
  script:
    - echo "Start deploying to Docker hub ..."
    - docker-compose up -d
    - docker push "$CD_DOCKER_HUB_IMAGE"
    - docker-compose down
    - docker volume prune  -f
	  - docker container prune  -f
    - echo "Done"
  only:
    - master