stages:
  - build
  - test
  - deploy 

build_dependencies:
  stage: build
  script:
    - echo "Start building dependencies ...."
    - mvn clean package
    - echo "Done"

build_docker_image:
  stage: build
  script:
    - echo "Start building docker image ..."
    - docker-compose --env-file ./Env/test.env up -d 
    - docker-compose down
    - echo "Done"

test_internal_API:
  stage: test
  script:
    - echo "Start testing internal API..."
    - mvn test
    - echo "Done"

deploy_project:
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker login -u "$CD_DOCKER_HUB_USER" -p "$CD_DOCKER_HUB_PASSWORD"
  script:
    - echo "Start deploying to Docker hub ..."
    - docker-compose --env-file ./Env/deploy.env up -d
    - docker push "$CD_DOCKER_HUB_IMAGE"
    - docker-compose down
    - echo "Done"
  only:
    - master