stages:
  - build
  - test
  - deploy 

build_project:
  stage: build
  script:
    - echo "Start building project ...."
    - echo "Done"

test_project:
  stage: test
  script:
    - echo "Start testing ..."
    - echo "Done"

deploy_project:
  stage: deploy
  script:
    - echo "Start deploying ..."
    - echo "Done"