verbal:
  jobTrigger: jobTrigger
  lambdaActionFile: lambdaActionFile
  jobPublishGroup: jobPublishGroup
  triggerPublishGroup: triggerPublishGroup
  jobFired: jobFired
  jobMisFired: jobMisFired
  jobStatus: jobStatus
  isRunning: IS RUNNING !!!
  isFinished: IS FINISHED !!!
  jobCompleted: jobCompleted
  healthCheckGroup: healthChecking