verbal:
  jobTrigger: jobTrigger
  lambdaActionFile: lambdaActionFile
  jobPublishGroup: jobPublishGroup
  triggerPublishGroup: triggerPublishGroup
  jobFired: jobFired
  jobMisFired: jobMisFired
  jobStatus: jobStatus