# This is a basic workflow to help you get started with Actions

name: GitlabSync

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  delete:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  gitlab-sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Github sync to Gitlab

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: wangchucheng/git-repo-sync@v0.1.0
        with:
          target-url: ${{secrets.GITLAB_URL}}
          target-username: ${{secrets.TARGET_USERNAME}}
          target-token: ${{secrets.TARGET_TOKEN}}

      # Runs a single command using the runners shell
      - name: Syncing master branch from GitHub to GitLab
        run: echo Syncing to GitLab...